// 화면 문구 (DESIGN.md 12장 부록 A). 화면에 보이는 글자는 여기서 가져다 써요.
// 사용법: Pickwise.t('screen1.title')  /  Pickwise.t('screen5.headline_template', { winner: '그리스' })
window.Pickwise = window.Pickwise || {};

Pickwise.copy = {
  common: {
    logo: 'Pickwise',
    next: '다음',
    back: '이전',
    loading_criteria: 'AI가 기준을 정리하고 있어요…',
    loading_analysis: '점수를 계산하고 있어요…',
    error_generic: '잠시 문제가 생겼어요. 다시 시도해 주세요.',
    empty_history: '아직 저장된 결정이 없어요.',
    privacy_notice: '실제 개인정보나 사내 정보는 입력하지 마세요.',
    status_done: '결정 완료',
    status_pending: '결정 중',
    status_recheck: '다시 확인 필요',
    back_aria: '이전 단계',
  },
  screen1: {
    header: '결정 입력',
    title: '어떤 결정이 고민되세요?',
    subtitle: '비교하고 싶은 주제와 선택지를 입력하면 AI가 더 나은 선택을 도와드려요.',
    label_topic: '결정 주제 입력',
    label_options: '선택지 입력',
    placeholder_topic: '예) 그리스 vs 이집트 어디로 갈지',
    add_option: '+ 선택지 추가',
    error_min_options: '비교하려면 선택지가 2개 이상 필요해요.',
    error_extract_fail: '주제와 선택지를 찾지 못했어요. 직접 입력해 주세요.',
    no_options_yet: '아직 선택지가 없나요?',
    ai_suggest_options: 'AI에게 후보 추천받기',
  },
  screen2: {
    header: '기준 선택',
    title: '어떤 기준으로 비교할까요?',
    subtitle: 'AI가 추천한 기준을 고르거나 직접 추가해 보세요.',
    ai_extra_title: '이런 기준도 고려해보세요',
    add_criteria: '+ 직접 추가',
    error_min: '기준을 1개 이상 선택해 주세요.',
    warn_many: '기준이 많으면 비교가 어려워져요. 5~6개를 추천해요.',
    missing_criteria_suggest: '{criteria}도 함께 비교해 보시겠어요?',
    add_criteria_placeholder: '기준 이름 (12자 이내)',
    error_duplicate: '이미 있는 기준이에요.',
    add_criteria_chip_aria: '{criteria} 기준 추가',
  },
  screen3: {
    header: '중요도 설정',
    title: '무엇이 더 중요한가요?',
    subtitle: '기준별 중요도를 0~100으로 조절해 주세요.',
    zero_weight_notice: '이 기준은 결과에 반영되지 않아요.',
    ratio_hint: '슬라이더 값은 기준끼리 비교하는 상대적 중요도예요.',
    all_zero_error: '중요도를 하나 이상 0보다 크게 설정해 주세요.',
  },
  screen4: {
    header: '정보 입력',
    title: '선택지에 대해 알고 있는 내용을 입력해 주세요.',
    subtitle: '정보가 많을수록 더 정확하게 비교할 수 있어요.',
    label_option_info: '{option}에 대해 알고 있는 내용',
    placeholder_option_info: '예) {option}에 대해 알고 있는 점이나 가고 싶은 이유를 적어 주세요.',
    attach_title: '자료 첨부 (선택사항)',
    attach_button: '+ 파일 추가',
    attach_hint: 'PDF / 이미지 / 문서',
    attach_guide: '분석할 때 참고가 필요한 정보를 입력해주세요. 특정 URL의 정보를 활용하고 싶다면, 웹페이지를 PDF로 저장해서 입력해주세요.',
    attach_help_aria: '웹페이지를 PDF로 저장하는 방법 보기',
    pdf_help_title: '웹페이지를 PDF로 저장하는 방법',
    pdf_help_sub: '브라우저 기본 기능으로 저장해요 (크롬, 엣지 등)',
    pdf_help_step1: '저장하려는 웹 페이지를 열어요.',
    pdf_help_step2: '키보드 Ctrl + P (맥은 Cmd + P)를 누르거나, 오른쪽 위 점 3개 메뉴에서 [인쇄]를 선택해요.',
    pdf_help_step3: "'프린터' 또는 '대상'을 [PDF로 저장(Save as PDF)]으로 바꿔요.",
    pdf_help_step4: '용지 방향, 여백 등 필요한 레이아웃을 조정해요.',
    pdf_help_step5: '[저장]을 눌러 원하는 위치에 파일을 저장해요.',
    pdf_help_after: "저장한 PDF는 아래 '+ 파일 추가'로 올려 주세요.",
    pdf_help_close: '닫기',
    no_info: '정보가 따로 없어요',
    analyze: '분석하기',
    error_file_type: '이 형식은 아직 지원하지 않아요. PDF 또는 텍스트 파일을 올려 주세요.',
    tab_free: '자유롭게 입력',
    tab_items: '항목별로 입력',
    tab_file: '자료 첨부',
    structured_preview_title: 'AI가 이렇게 이해했어요',
    structured_preview_hint: '틀린 부분이 있으면 직접 고쳐 주세요.',
  },
  screen5: {
    header: '분석 결과',
    title: '분석 결과',
    subtitle: '입력한 기준을 바탕으로 두 선택지를 비교했어요.',
    score_unit: '점',
    section_compare: '기준별 비교',
    section_ai: 'AI 설명',
    ai_explain_label: 'AI 설명 · {winner}가 앞선 이유',
    section_sensitivity: '민감도 분석',
    section_whatif: 'What-if 분석',
    headline_template: '현재 설정한 중요도와 입력한 정보를 기준으로는 {winner}의 총점이 더 높게 계산되었어요.',
    badge_user: '사용자 입력',
    badge_file: '첨부 자료',
    badge_ai: 'AI 추정 · 추가 확인 권장',
    disclaimer: '이 결과는 입력한 정보와 중요도를 기준으로 한 계산이며, 최종 결정은 사용자가 내려요.',
    tie_notice: '두 선택지의 점수 차이가 거의 없어요. 중요도를 다시 확인해 보세요.',
    evidence_label: '근거',
    no_info_label: '정보 부족',
    excluded_notice: 'AI도 근거를 찾지 못한 기준 {n}개({criteria})는 총점에서 제외했어요.',
    sensitivity_flip_template: "'{criteria}'의 중요도를 현재 {from}%에서 {to}% 이상으로 높이면 {option}의 총점이 더 높아져요.",
    sensitivity_close_template: "'{criteria}'의 중요도를 {from}%에서 {to}%로 높이면 두 선택지의 차이가 거의 없어져요.",
    sensitivity_stable_template: "'{criteria}'의 중요도를 바꿔도 순위는 바뀌지 않아요.",
    whatif_result_template: "'{condition}' 조건에서는 {winner}의 총점이 더 높게 계산돼요.",
    select_option_cta: '이 선택지로 결정',
  },
  screen6: {
    header: '다음 결정',
    title: '이 결정 다음에도 고민할 게 있나요?',
    ai_recommend: 'AI 추천',
    custom_input: '+ 새로운 고민 직접 입력',
    placeholder_custom: '예) 어떤 숙소가 좋을까?',
    start_new: '새 결정 시작하기',
    context_greeting_template: "결정하신 '{selected}' 다음으로 이런 고민을 이어서 비교할 수 있어요.",
    continue_button: '다음 고민 이어가기',
  },
  history: {
    title: '나의 결정',
    node_result_template: '→ {selected}',
    recheck_notice: '앞선 결정이 바뀌어서 다시 확인이 필요해요.',
    empty: '아직 저장된 결정이 없어요.',
  },
};

Pickwise.t = function (key, values) {
  const [group, name] = key.split('.');
  let text = (Pickwise.copy[group] || {})[name];
  if (text == null) return key;
  if (values) text = text.replace(/\{(\w+)\}/g, (m, k) => (values[k] != null ? values[k] : m));
  return text;
};
